version: '3.8'

services:
  db:
    image: postgres:15
    container_name: ocularr-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ocularr-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: ocularr-backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: ${NODE_ENV:-production}
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      JWT_SECRET: ${JWT_SECRET}
      TMDB_API_KEY: ${TMDB_API_KEY}
      BACKEND_PORT: ${BACKEND_PORT:-3001}
      APP_PORT: ${APP_PORT}
      FRONTEND_URL: ${FRONTEND_URL:-}
    volumes:
      - ./uploads:/app/uploads
    networks:
      - ocularr-network

  frontend:
    build: 
      context: ./frontend
    container_name: ocularr-frontend
    depends_on:
      - backend
    ports:
      - "${APP_PORT}:80"
    networks:
      - ocularr-network

networks:
  ocularr-network:
    driver: bridge

volumes:
  postgres_data: